{
 "title": "V2ray",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "访问次数",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"access\",src!~\"^192*\",dst!~\"^192*\"}",
     "legendFormat": "{{dst}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "流量统计",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (type) (sum_over_time({type=\"traffic\"} | json | unwrap value [$__interval]))"
    },
    {
     "expr": "sum by (type) (sum_over_time({type=\"traffic\"} | json | unwrap value [$__interval]))"
    }
   ]
  },
  {
   "title": "实时流量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (type,link,name) (sum_over_time({type=\"traffic\"} | json | unwrap value [$__interval]))",
     "legendFormat": "{{name}}_{{link}}"
    }
   ]
  }
 ]
}